version: '3'

services:

  minio:
      image: minio/minio
      environment:
          MINIO_ROOT_USER: access1234
          MINIO_ROOT_PASSWORD: secret1234
      volumes:
          - ./data/minio:/data
      command: server /data --console-address ":9001"
      ports:
          - 9090:9000
          - 9001:9001